# Generated by Django 3.0.7 on 2020-10-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20201012_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subject_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='subjects',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='student_management_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='students',
            name='interests',
            field=models.ManyToManyField(related_name='interested_students', to='student_management_app.Subjects'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
